ALTER TABLE volumes ALTER COLUMN id TYPE VARCHAR(255);
ALTER TABLE volumes ALTER COLUMN account_id TYPE VARCHAR(255);

ALTER TABLE snapshots ALTER COLUMN id TYPE VARCHAR(255);
ALTER TABLE snapshots ALTER COLUMN account_id TYPE VARCHAR(255);
ALTER TABLE snapshots ALTER COLUMN database_id TYPE VARCHAR(255);
ALTER TABLE snapshots ALTER COLUMN volume_id TYPE VARCHAR(255);
