CREATE TABLE IF NOT EXISTS vpcs (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cidr_block VARCHAR(50) NOT NULL,
    bridge_name VARCHAR(100) NOT NULL,
    subnet VARCHAR(50) NOT NULL,
    gateway VARCHAR(50) NOT NULL,
    tenant_id VARCHAR(36) NOT NULL,
    status VARCHAR(50) NOT NULL,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vpcs_tenant_id ON vpcs(tenant_id);
