@baseUrl = http://localhost:8087/api/v1/rds
@apiKey = your_access_key_id:your_secret_access_key

### 
# 1. Health Ping
GET {{baseUrl}}/health/ping


### 
# 2. Complete Health Status
GET {{baseUrl}}/health/status

